# Podman-specific compose file
# Use this if you're running Podman and encounter issues with docker-compose.yml
# Usage: podman-compose -f podman-compose.yml up

version: '3.8'

services:
  # LocalStack - Local AWS cloud stack for S3 emulation
  localstack:
    image: docker.io/localstack/localstack:latest
    container_name: s3-manager-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 0
      DATA_DIR: /tmp/localstack/data
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - localstack_data:/tmp/localstack:Z
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh:Z,ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # S3 Manager application
  s3-manager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: s3-manager-app
    ports:
      - "8080:8080"
    environment:
      LOCAL_DEV_MODE: "true"
      FLASK_DEBUG: "true"
      SECRET_KEY: "dev-secret-key-change-in-production"
      AZURE_AD_TENANT_ID: ""
      AZURE_AD_CLIENT_ID: ""
      AZURE_AD_CLIENT_SECRET: ""
      PIM_ENABLED: "false"
      DEFAULT_ROLE: "S3-Admin"
      S3_ENDPOINT: "http://localstack:4566"
      S3_ACCESS_KEY: "test"
      S3_SECRET_KEY: "test"
      S3_REGION: "us-east-1"
      S3_USE_SSL: "false"
      S3_VERIFY_SSL: "false"
      SESSION_COOKIE_SECURE: "false"
    volumes:
      - ./app:/app/app:Z
      - ./config.py:/app/config.py:Z
      - ./run.py:/app/run.py:Z
    depends_on:
      localstack:
        condition: service_healthy

volumes:
  localstack_data:
