---
apiVersion: v1
kind: Namespace
metadata:
  name: s3-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-pvc
  namespace: s3-manager
  labels:
    app: localstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # kind clusters use local-path provisioner by default (standard storage class)
  # minikube uses hostpath provisioner
  # k3s uses local-path provisioner
  # No need to specify storageClassName - uses cluster default
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: s3-manager
  labels:
    app: localstack
spec:
  type: ClusterIP
  ports:
    - port: 4566
      targetPort: 4566
      protocol: TCP
      name: gateway
  selector:
    app: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: s3-manager
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          ports:
            - containerPort: 4566
              name: gateway
          env:
            - name: SERVICES
              value: "s3"
            - name: DEBUG
              value: "0"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            # Enable persistence (data survives pod restarts)
            - name: PERSISTENCE
              value: "1"
          volumeMounts:
            # Mount to /var/lib/localstack instead of /tmp/localstack to avoid conflicts
            - name: localstack-data
              mountPath: /var/lib/localstack
            - name: init-script
              mountPath: /etc/localstack/init/ready.d
          livenessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: localstack-data
          # Using PVC for persistent storage across pod restarts
          # kind, minikube, and k3s all support dynamic provisioning
          persistentVolumeClaim:
            claimName: localstack-pvc
        - name: init-script
          configMap:
            name: localstack-init
            defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init
  namespace: s3-manager
data:
  init.sh: |
    #!/bin/bash
    echo "Initializing LocalStack S3 buckets..."
    sleep 5
    
    awslocal s3 mb s3://test-bucket
    awslocal s3 mb s3://demo-bucket
    awslocal s3 mb s3://uploads
    
    echo "Sample file 1" > /tmp/sample1.txt
    echo "Sample file 2" > /tmp/sample2.txt
    awslocal s3 cp /tmp/sample1.txt s3://demo-bucket/sample1.txt
    awslocal s3 cp /tmp/sample2.txt s3://demo-bucket/sample2.txt
    
    awslocal s3 cp /tmp/sample1.txt s3://demo-bucket/folder1/file1.txt
    awslocal s3 cp /tmp/sample2.txt s3://demo-bucket/folder1/folder2/file2.txt
    
    echo "LocalStack S3 initialization complete!"
    awslocal s3 ls
